// <auto-generated />
using System;
using BlissRecruitment.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlissRecruitment.Infra.Data.Migrations
{
    [DbContext(typeof(BlissRecruitmentContext))]
    partial class BlissRecruitmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlissRecruitment.Domain.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ThumbUrl")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 782, DateTimeKind.Local).AddTicks(6698),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 2L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(2630),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 3L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(3067),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 4L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(3162),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 5L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(3246),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 6L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(3515),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 7L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(3573),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 8L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(3618),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 9L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(3661),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 10L,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2020, 10, 5, 0, 38, 57, 785, DateTimeKind.Local).AddTicks(3709),
                            QuestionDescription = "Favourite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        });
                });

            modelBuilder.Entity("BlissRecruitment.Domain.Models.QuestionChoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionChoices");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Choice = "Swift",
                            QuestionId = 1L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 2L,
                            Choice = "Python",
                            QuestionId = 1L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 3L,
                            Choice = "Objective-C",
                            QuestionId = 1L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 4L,
                            Choice = "Ruby",
                            QuestionId = 1L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 5L,
                            Choice = "Swift",
                            QuestionId = 2L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 6L,
                            Choice = "Python",
                            QuestionId = 2L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 7L,
                            Choice = "Objective-C",
                            QuestionId = 2L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 8L,
                            Choice = "Ruby",
                            QuestionId = 2L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 9L,
                            Choice = "Swift",
                            QuestionId = 3L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 10L,
                            Choice = "Python",
                            QuestionId = 3L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 11L,
                            Choice = "Objective-C",
                            QuestionId = 3L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 12L,
                            Choice = "Ruby",
                            QuestionId = 3L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 13L,
                            Choice = "Swift",
                            QuestionId = 4L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 14L,
                            Choice = "Python",
                            QuestionId = 4L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 15L,
                            Choice = "Objective-C",
                            QuestionId = 4L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 16L,
                            Choice = "Ruby",
                            QuestionId = 4L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 17L,
                            Choice = "Swift",
                            QuestionId = 5L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 18L,
                            Choice = "Python",
                            QuestionId = 5L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 19L,
                            Choice = "Objective-C",
                            QuestionId = 5L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 20L,
                            Choice = "Ruby",
                            QuestionId = 5L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 21L,
                            Choice = "Swift",
                            QuestionId = 6L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 22L,
                            Choice = "Python",
                            QuestionId = 6L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 23L,
                            Choice = "Objective-C",
                            QuestionId = 6L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 24L,
                            Choice = "Ruby",
                            QuestionId = 6L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 25L,
                            Choice = "Swift",
                            QuestionId = 7L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 26L,
                            Choice = "Python",
                            QuestionId = 7L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 27L,
                            Choice = "Objective-C",
                            QuestionId = 7L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 28L,
                            Choice = "Ruby",
                            QuestionId = 7L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 29L,
                            Choice = "Swift",
                            QuestionId = 8L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 30L,
                            Choice = "Python",
                            QuestionId = 8L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 31L,
                            Choice = "Objective-C",
                            QuestionId = 8L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 32L,
                            Choice = "Ruby",
                            QuestionId = 8L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 33L,
                            Choice = "Swift",
                            QuestionId = 9L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 34L,
                            Choice = "Python",
                            QuestionId = 9L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 35L,
                            Choice = "Objective-C",
                            QuestionId = 9L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 36L,
                            Choice = "Ruby",
                            QuestionId = 9L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 37L,
                            Choice = "Swift",
                            QuestionId = 10L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 38L,
                            Choice = "Python",
                            QuestionId = 10L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 39L,
                            Choice = "Objective-C",
                            QuestionId = 10L,
                            Votes = 0
                        },
                        new
                        {
                            Id = 40L,
                            Choice = "Ruby",
                            QuestionId = 10L,
                            Votes = 0
                        });
                });

            modelBuilder.Entity("BlissRecruitment.Domain.Models.QuestionChoice", b =>
                {
                    b.HasOne("BlissRecruitment.Domain.Models.Question", "Question")
                        .WithMany("QuestionChoices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
